//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualiserWebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.ModuleUserRoles = new HashSet<ModuleUserRole>();
            this.Tests = new HashSet<Test>();
            this.Topics = new HashSet<Topic>();
        }
    
        public int ModuleID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string moduleCode { get; set; }
        public string moduleName { get; set; }
        public Nullable<bool> archived { get; set; }
    
        public virtual ICollection<ModuleUserRole> ModuleUserRoles { get; set; }
        public virtual ICollection<Test> Tests { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Topic> Topics { get; set; }
    }
}
