//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualiserWebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.TestQuestions = new HashSet<TestQuestion>();
            this.Topics = new HashSet<Topic>();
        }
    
        public int QuestionID { get; set; }
        public string qText { get; set; }
        public string qCorrectAnswer { get; set; }
        public string qDistractor1 { get; set; }
        public string qDistractor2 { get; set; }
        public string qDistractor3 { get; set; }
    
        public virtual ICollection<TestQuestion> TestQuestions { get; set; }
        public virtual ICollection<Topic> Topics { get; set; }
    }
}
