//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualiserWebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public Test()
        {
            this.TestQuestions = new HashSet<TestQuestion>();
        }
    
        public int TestID { get; set; }
        public int ModuleID { get; set; }
        public string testTitle { get; set; }
        public string testType { get; set; }
        public int totalAttempts { get; set; }
        public int uniqueAttempts { get; set; }
        public decimal averageMark { get; set; }
        public Nullable<System.DateTime> testDate { get; set; }
        public System.DateTime uploadDate { get; set; }
        public int assessor { get; set; }
        public int testMark { get; set; } //i dont know why i added this?
    
        public virtual Module Module { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<TestQuestion> TestQuestions { get; set; }
    }
}
