//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualiserWebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public Topic()
        {
            this.Modules = new HashSet<Module>();
            this.Questions = new HashSet<Question>();
        }
    
        public int TopicID { get; set; }
        public string topicName { get; set; }
        public string topicDescription { get; set; }
    
        public virtual ICollection<Module> Modules { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
    }
}
