//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualiserWebProject.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public User()
        {
            this.Modules = new HashSet<Module>();
            this.ModuleUserRoles = new HashSet<ModuleUserRole>();
            this.Tests = new HashSet<Test>();
            this.Roles = new HashSet<Role>();
        }

        //Autogenerated | Annotation - Key (uniquely identify entity)
        [Key]
        public int UserID { get; set; }

        //Annotation - Display Name, Required and error message, String length
        [Display(Name = "First Name")]
        [Required(ErrorMessage = "Please enter your first name.", AllowEmptyStrings = false)]
        [StringLength(225)]
        public string userFirstName { get; set; }
        //Annotation - Display Name, Required and error message, String length
        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "Please enter your last name.", AllowEmptyStrings = false)]
        [StringLength(225)]
        public string userLastName { get; set; }

        //Annotation - Display Name, string length
        [Display(Name = "Title")]
        [StringLength(225)]
        public string title { get; set; }

        //Annotation - Display Name, Required, email address Regex 
        [Display(Name = "Email Address")]
        [Required(ErrorMessage = "Please enter an email address.", AllowEmptyStrings = false)]
        [RegularExpression(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,4})+)$", ErrorMessage = "Please enter a valid email")] 
        [StringLength(50)]
        public string emailAddress { get; set; }

        //Annotation - Display Name, Required, Password Data Format, Error Message, String length
        [Display(Name = "Password")]
        [Required(ErrorMessage = "Please enter a password.", AllowEmptyStrings = false)]
        [DataType(DataType.Password)]
        [StringLength(50)]
        public string password { get; set; }

        //Autogenerated
        public string salt { get; set; }
    
        public virtual ICollection<Module> Modules { get; set; }
        public virtual ICollection<ModuleUserRole> ModuleUserRoles { get; set; }
        public virtual ICollection<Test> Tests { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
