//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualiserWebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Modules = new HashSet<Module>();
            this.ModuleUserRoles = new HashSet<ModuleUserRole>();
            this.Tests = new HashSet<Test>();
            this.Roles = new HashSet<Role>();
        }
    
        public int UserID { get; set; }
        public string userFirstName { get; set; }
        public string userLastName { get; set; }
        public string title { get; set; }
        public string emailAddress { get; set; }
        public string password { get; set; }
        public string salt { get; set; }
    
        public virtual ICollection<Module> Modules { get; set; }
        public virtual ICollection<ModuleUserRole> ModuleUserRoles { get; set; }
        public virtual ICollection<Test> Tests { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
